Map<String, Map<String, double>> emotionProfiles = {

  "Happy": {
    "energy": 90,
    "danceability": 90,
    "positiveness": 95,
    "tempo": 80,
    "loudness": 80,
    "speechiness": 20,
    "liveness": 70,
    "acousticness": 20,
    "instrumentalness": 10,
    "popularity": 80,
  },

  "Sad": {
    "energy": 20,
    "danceability": 30,
    "positiveness": 10,
    "tempo": 30,
    "loudness": 30,
    "speechiness": 20,
    "liveness": 20,
    "acousticness": 80,
    "instrumentalness": 60,
    "popularity": 60,
  },

  "Angry": {
    "energy": 95,
    "danceability": 60,
    "positiveness": 20,
    "tempo": 90,
    "loudness": 95,
    "speechiness": 30,
    "liveness": 80,
    "acousticness": 10,
    "instrumentalness": 10,
    "popularity": 70,
  },

  "Fear": {
    "energy": 20,
    "danceability": 20,
    "positiveness": 20,
    "tempo": 20,
    "loudness": 20,
    "speechiness": 20,
    "liveness": 20,
    "acousticness": 80,
    "instrumentalness": 60,
    "popularity": 50,
  },

  "Neutral": {
    "energy": 50,
    "danceability": 50,
    "positiveness": 50,
    "tempo": 50,
    "loudness": 50,
    "speechiness": 50,
    "liveness": 50,
    "acousticness": 50,
    "instrumentalness": 50,
    "popularity": 70,
  },

  "Surprise": {
    "energy": 90,
    "danceability": 90,
    "positiveness": 80,
    "tempo": 85,
    "loudness": 80,
    "speechiness": 40,
    "liveness": 80,
    "acousticness": 20,
    "instrumentalness": 10,
    "popularity": 80,
  },

  "Disgust": {
    "energy": 10,
    "danceability": 20,
    "positiveness": 10,
    "tempo": 20,
    "loudness": 20,
    "speechiness": 20,
    "liveness": 10,
    "acousticness": 90,
    "instrumentalness": 80,
    "popularity": 40,
  },
};